version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=shortener
      - POSTGRES_HOST=db
    depends_on:
      - db
  db:
    image: postgres:14
    restart: unless-stopped
    ports:
      - 5436:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=shortener
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
